[pytest]
markers =
    activities: mark a test as a workflow activities test
    ai_assistant: mark a test as an AI Assistant functionality test
    brain_region: mark a test as a brain_region test
    build_em_mapping: mark a test as a build EM mapping workflow test
    build_page: mark a test as a build_page test
    build_single_neuron: mark a test as a build single neuron functionality test
    data_circuit: mark a test as a data circuit test
    explore_page: mark a test as an explore_page test
    login_page: mark a test as a login_page test
    no_auto_nav: Prevents automatic navigation to login/lab pages before tests
    process_data: mark a test as a process data workflow test
    project_credits: mark a test as a project credits test
    project_page: mark a test as a project_page test
    simulate: mark a test as a simulation workflow test
    skip_module(reason): mark an entire module to be skipped
    smoke: mark a test as a smoke test for CI/CD stability
    workflow: mark a test as a workflow functionality test
    workflow_build: mark a test as a workflow build functionality test

addopts =
    --html=report.html
    --alluredir=allure_reports
    --ignore=tests/test_homepage.py
    --ignore=tests/test_pricing.py
    --ignore=tests/test_morphology.py
    --ignore=tests/test_vl_overview.py
    --ignore=tests/test_explore_ndensity.py
    --ignore=tests/test_explore_ephys.py
    --ignore=tests/test_build.py

log_cli = true
log_cli_level = INFO