from selenium.webdriver.common.by import By


class ExplorePageLocators:
    EXPLORE_URL = (By.XPATH, "//a[@href='/mmb-beta/explore']")
    EXPLORE_LINK1 = (By.XPATH, "//a[@href='/mmb-beta/explore/simulation-campaigns']//h1[text()='Brain & cells annotations']")
    EXPLORE_TITLE = (By.XPATH, "//h1[text()='Explore']")
    BRAIN_CELL_ANNOTATIONS = (By.XPATH, "//h1[text()='Brain & cells annotations']")
    BRAIN_CELL_ANNOTATIONS_URL = (By.XPATH,  "//a[@href='/mmb-beta/simulation-campaigns']")
    EXPERIMENTAL_DATA = (By.XPATH, "//h2[contains(text(), 'Experimental Data')]")
    EXPERIMENTAL_DATA_BUTTON = (By.XPATH, "//h2[contains(text(),'Experimental Data')]//ancestor::div[2]")
    BRAIN_MODELS = (By.XPATH, "//h2[text()='Brain Models']")
    SIMULATIONS = (By.XPATH, "//h2[text()='Simulations']")
    PORTALS = (By.XPATH, "//h2[text()='Portals']")
    GALLERY = (By.XPATH, "//h2[text()='Gallery']")
    LITERATURE = (By.XPATH, "//h2[text()='Literature']")
    NEURON_ELECTROPHYSIOLOGY = (By.XPATH, "//h3[contains(text(),'Neuron electrophysiology')]//ancestor::a[1][@href='/mmb-beta/explore/electrophysiology']")
    NEURON_MORPHOLOGY = (By.XPATH, "//h3[contains(text(),'Neuron morphology')]//ancestor::a[1][@href='/mmb-beta/explore/morphology']")
    BOUTON_DENSITY = (By.XPATH, "//h3[contains(text(),'Bouton density')]//ancestor::a[1][@href='/mmb-beta/explore/bouton-density']")
    NEURON_DENSITY = (By.XPATH, "//h3[contains(text(),'Neuron density')]//ancestor::a[1][@href='/mmb-beta/explore/neuron-density']")
    LAYER_THICKNESS = (By.XPATH, "//h3[contains(text(),'Layer thickness')]//ancestor::a[1][@href='/mmb-beta/explore/layer-thickness']")
    SYNAPSE_PER_CONNECTION = (By.XPATH, "//h3[contains(text(),'Synapse per connection')]//ancestor::a[1][@href='/mmb-beta/explore/synapse-per-connection']")
    NEURON_EPHYS_PAGE_TITLE = (By.XPATH, "//div[contains(text(),'Neuron electrophysiology')]")
    SEARCH_LABEL = (By.XPATH, "//span[contains(@class, 'anticon-search') and @aria-label='search']")
    SEARCH_INPUT_FIELD = (By.XPATH, "//span[starts-with(@class,'ant-input-affix-wrapper ant-input-affix-wrapper-lg')]/input[@type='text' and starts-with(@class,'ant-input ant-input-lg')]")
    BRAIN_REGION_COLUMN = (By.XPATH, "//div[text()='Brain Region']")
    E_TYPE_COLUMN = (By.XPATH, "//div[text()='E-Type']")
    NAME_REGION_COLUMN = (By.XPATH, "//div[text()='Name']")
    SPECIES_REGION_COLUMN = (By.XPATH, "//div[text()='Species']")
    CONTRIBUTORS_COLUMN = (By.XPATH, "//div[text()='Contributors']")
    CREATION_DATE_COLUMN = (By.XPATH, "//div[text()='Creation date']")
    CLEAR_FILTERS_BTN = (By.XPATH, "//button[@type='button']/span[text()='Clear filters']")
    FILTER_BTN = (By.XPATH, "//button[@type='button' and starts-with(@class, 'filters_filterButton')]")
    FILTER_CLOSE_BTN = (By.XPATH, "//button[@type='button']/span[@role='img' and @class='anticon anticon-close']")
    SIDE_BAR_EXPLORE_BTN = (By.XPATH, "//div[starts-with(@class,'sidebar_side')]//a[@href='/mmb-beta/explore' and text()='Explore']")
    SIDE_BAR_PLUS_BTN = (By.XPATH, "//div[starts-with(@class,'sidebar_side')]//button[starts-with(@class, 'ant-btn css')]")
    SIDE_BAR_MENU = (By.XPATH, "//aside/div[starts-with(@class,'sidebar_expanded__')]")
    SIDE_BAR_MENU_CLOSE_BTN = (By.XPATH, "//button[@type='button' and starts-with(@class, 'ant-btn')]/span[@class='ant-btn-icon']")