# Copyright (c) 2024 Blue Brain Project/EPFL
# Copyright (c) 2025 Open Brain Institute
# SPDX-License-Identifier: Apache-2.0



from selenium.webdriver.common.by import By


class LandingLocators:
    BANNER_TITLE = (By.XPATH, "//h1[contains(text(),'Create your Virtual Lab to build digital brain mod')]")
    BIG_IMG1 = (By.XPATH, "(//div[starts-with(@class,'SanityContentPreview-module__hsTF2G__vignette')])[1]")
    BIG_IMG2 = (By.XPATH, "(//div[starts-with(@class,'SanityContentPreview-module__hsTF2G__vignette')])[2]")
    BIG_IMG3 = (By.XPATH, "(//div[starts-with(@class,'SanityContentPreview-module__hsTF2G__vignette')])[3]")
    DIGITAL_BRAINS_VIDEO = (By.XPATH, "//div[@class='sanity-content-video-module__8kGZUG__sanityContentVideo "
                                  "styles-module__5IYxQa__blockMedium']")
    DIGITAL_BRAINS_PLAY_BTN = (By.CSS_SELECTOR, "button[aria-label='play video']")
    DIGITAL_BRAINS_PAUSE_BTN = (By.CSS_SELECTOR, "button[aria-label='pause video']")
    DIGITAL_BRAINS_VIDEO_CURRENT_STEP = (By.CSS_SELECTOR, ".sanity-content-video-module__8kGZUG__currentStep")
    DIGITAL_BRAINS_VIDEO_STEP = (By.XPATH, "//button[@class='sanity-content-video-module__8kGZUG__step']")
    GOTO_LAB = (By.XPATH, "//a[@href='/app/virtual-lab']")
    HERO_BACKGROUND_IMG = (By.CSS_SELECTOR, ".Hero-module__E0OG9W__background")
    HERO_BACKGROUND_VIDEO = (By.CSS_SELECTOR, ".Hero-module__E0OG9W__show")
    NAV_ABOUT = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/about']")
    NAV_MISSION = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/mission']")
    NAV_NEWS = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/news']")
    NAV_PRICING = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/pricing']")
    NAV_TEAM = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/team']")
    NAV_RESOURCES = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/resources']")
    NAV_CONTACT = (By.XPATH, "//div[@class='Menu-module__CnaVha__items']/a[@href='/contact']")
    OBI_LOGO = (By.XPATH, "(//h2[contains(text(),'Open Brain Institute')])[1]")
    PARA_TEXT = (By.XPATH, "//div[contains(@class, 'Text-module__KTJYiG__text')]")
    P_TEXT1 = (By.XPATH, "(//div[@class='SanityContentPreview-module__hsTF2G__text'])[1]")
    P_TEXT2 = (By.XPATH, "(//div[@class='SanityContentPreview-module__hsTF2G__text'])[2]")
    P_TEXT3 = (By.XPATH, "(//div[@class='SanityContentPreview-module__hsTF2G__text'])[3]")
    P_TEXT4 = (By.XPATH, "(//div[@class='SanityContentPreview-module__hsTF2G__text'])[4]")
    P_TEXT5 = (By.XPATH, "//div[@class='Text-module__KTJYiG__text']/p[contains(text(), 'Digital brains are advanced')]")
    # OBI_LOGO = (By.CSS_SELECTOR, ".Menu-module__CnaVha__logo")
    SECTION_BTN1 = (By.XPATH, "(//button[starts-with(@class,'SanityContentPreview-module__hsTF2G__button')])[1]")
    SECTION_BTN2 = (By.XPATH, "(//button[starts-with(@class,'SanityContentPreview-module__hsTF2G__button')])[2]")
    SECTION_BTN3 = (By.XPATH, "(//button[starts-with(@class,'SanityContentPreview-module__hsTF2G__button')])[3]")
    SECTION_BTN4 = (By.XPATH, "(//button[starts-with(@class,'SanityContentPreview-module__hsTF2G__button')])[4]")
    SECTION_BTN5 = (By.XPATH, "(//button[starts-with(@class,'SanityContentPreview-module__hsTF2G__button')])[5]")
    HORIZONTAL_CARDS_SECTION1 = (By.XPATH, "(//div[starts-with(@class,'swipeable-cards-list_scroll')])[1]")
    HORIZONTAL_CARDS_SECTION2 = (By.XPATH, "(//div[starts-with(@class,'swipeable-cards-list_scroll')])[2]")
    NEWS_CARD1 = (By.XPATH, "(//button[starts-with(@class,'NewsCard')])[1]")
    NEWS_CARD2 = (By.XPATH, "(//button[starts-with(@class,'NewsCard')])[2]")
    NEWS_CARD3 = (By.XPATH, "(//button[starts-with(@class,'NewsCard')])[3]")
    NEWS_CARD4 = (By.XPATH, "(//button[starts-with(@class,'NewsCard')])[4]")
    NEWS_CARD_CONTENT1 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_content')])[1]")
    NEWS_CARD_CONTENT2 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_content')])[2]")
    NEWS_CARD_CONTENT3 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_content')])[3]")
    NEWS_CARD_CONTENT4 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_content')])[4]")
    NEWS_CARD_PIC1 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_picture')])[1]")
    NEWS_CARD_PIC2 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_picture')])[2]")
    NEWS_CARD_PIC3 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_picture')])[3]")
    NEWS_CARD_PIC4 = (By.XPATH, "(//div[starts-with(@class,'NewsCard_picture')])[4]")
    TITLE_ACCELERATE = (By.XPATH, "//h1[normalize-space()='Accelerating neuroscience research']")
    TITLE_DIG_BRAIN = (By.XPATH, "//h1[normalize-space()='What are digital brains?']")
    TITLE_WHO = (By.XPATH, "//h1[normalize-space()='Who is behind the Open Brain Institute']")
    TITLE_NEWS = (By.XPATH, "//h1[normalize-space()='News and events']")
    TOP_MENU = (By.CSS_SELECTOR, "(div[id='LandingPage/menu'])")
    TOP_ABOUT = (By.XPATH, "(//a[@href='/about'])[1]")
    TOP_MISSION = (By.XPATH, "(//a[@href='/mission'])[1]")
    TOP_NEWS = (By.XPATH, "(//a[@href='/news'])[1]")
    TOP_PRICING = (By.XPATH, "(//a[@href='/pricing'])[1]")
    TOP_TEAM = (By.XPATH, "(//a[@href='/team'])[1]")
    TOP_RESOURCES = (By.XPATH, "(//a[@href='/resources'])[1]")
    TOP_CONTACT = (By.XPATH, "(//a[@href='/contact'])[1]")
    TOP_MENU_LOGO = (By.XPATH, "//a[starts-with(@class,'Menu_logo')]")
    VIDEO_TITLE1 = (By.XPATH, "//h3[normalize-space()='01. Fill with Neurons']")
    VIDEO_CONTAINER = (By.XPATH, "(//div[starts-with(@class,'sanity-content-video-module')])[1]")
    VIDEO_POINTER = (By.CSS_SELECTOR, ".Video-module__ZeAqaq__pointer")


